Name=input("Enter Name")
Branch=input("Enter Branch")
Gender=input("Enter Gender")
College=input("Enter College")
Age=int(input("Enter Age"))
print("Name:",Name)
print("Branch:",Branch)
print("Gender:",Gender)
print("College:",College)
print("Age:",Age)
